### ISSUE TITLE
use codeclimate compatible versions only

### ISSUE THREAD

**Issue by akatov** [tallarium/lenz#10]
discuss

**Comment by kmoe** [comment]
To summarise my thoughts on linting and Codeclimate:

The purpose of linting is to
 -  **catch possible errors in code before it lands in master**, 
 -  **improve maintainability** (by enforcing a code style and removing redundant code). 

The bottom line is that the user will get a better experience because he won't experience the bugs caused by certain types of bad code, and will benefit from quicker fixes and new features due to greater dev velocity.

Since we are a small shop not wired up to collect and analyse this kind of data, I expect we don't know the impact of the time spent working on linting on key metrics like the number of production bugs that could have been prevented with better linting, or that have been prevented by good linting.

So it is up for debate whether Codeclimate contributes positively to our bottom line. But I reckon it does not provide an adequate return for the time and money (presumably) we spend on it. I think we would get the same benefits by doing the following:

---

 - use lenz as a Tallarium-wide lint rule authority for all repos that need linting
 - encourage devs to install linters in their local editor or dev environment
 - use a pre-push git hook to fail pushes to any branch if there are lint fails
    - dev will have to either fix the issue, or add an ignore directive until such time as the lint rule can be changed upstream
 - use a separate CI run (as suggested in https://github.com/tallarium/sark/pull/118#issuecomment-351685621) to provide lint commit status on PR commits and prevent merge when red

---

In addition, we wouldn't have to make complex changes as mentioned in https://github.com/tallarium/sark/pull/118#issuecomment-351998515, using older dependencies and holding back releases just to make Codeclimate work.

The only benefit we would lose from Codeclimate is the web interface and issue triaging, and since they don't integrate with GitHub it looks like issues on Codeclimate have no effect in our process after the commit status stage (at which the developer either fixes or ignores them to so he can merge the PR). Codeclimate's ratings, maintainability scores, trends, and other analysis are also of little practical value.

**Comment by msz** [comment]
While I think keeping linter versions fixed to Codeclimate versions would not be a big problem, we frequently use linter plugins which are not supported by Codeclimate, and that was the reason behind moving linting to CI in https://github.com/tallarium/sark. So I think moving linting to a separate CI job would be a good solution.

However I think it's still worth keeping Codeclimate around because it provides complexity analysis and code duplication analysis which are quite useful.

**Comment by jeffjewiss** [comment]
I agree with the points Katy made and that it's hard to tell if Codeclimate is contributing positively to our bottom line.

I'm also concerned that we're spending more time fighting with, and fixing things for Codeclimate than we are gaining benefits from having it as part of our toolchain. Additionally we're overcomplicating our linting setup and dependencies just for Codelimate.

I agree that the complexity analysis and code duplication analysis are useful, but I would ask: could we get the same output from a simpler CI job, and do we ever go back and fix the issues that we have ignored or otherwise left unresolved in some way?

**Comment by akatov** [comment]
Let's do linting as a (possibly separate) CI job. Use Codeclimate's eslint and tslint only if they work with our current dependency versions in lenz. Otherwise just turn them off and use codeclimate's other engines.
